workflows:
  android-workflow:
    name: Android Workflow
    environment:
      groups:
        - android_credentials
    scripts:
      - name: Get packages
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
      - name: Build AAB
        script: flutter build appbundle --release
    artifacts:
      - build/app/outputs/**/*.apk
      - build/app/outputs/**/*.aab
